name: Publish
on:
  push:
    branches:
      - main
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          package-manager-cache: false # Disable automatic npm caching if not required
      - name: Install Dependencies
        run: npm ci
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
